#!/usr/bin/env bash
# condense-context.sh — Context condensation for Smart Ralph coordinator session.
# Implements: arg parsing, degradation check, archive, gate re-check,
#   min-pointer prefix condensation, pointer atomicity, progress.md split,
#   metrics logging, and archive pruning.
#
# Usage:
#   condense-context.sh <spec_path> --mode <proactive|reactive|emergency>
#   Exit 0: condensed OR skipped-as-noop OR degraded-gracefully
#   Exit 1: unexpected internal error
#   stdout: one-line summary  e.g.  "condensed: chat 1840->210, progress 430->95"

set -euo pipefail

# Source shared helpers (lib-context.sh)
CLAUDE_PLUGIN_ROOT="$(git -C "${1:-.}" rev-parse --show-toplevel 2>/dev/null || echo "$PWD")/plugins/ralphharness"
source "${CLAUDE_PLUGIN_ROOT}/hooks/scripts/lib-context.sh"

# --- Arg Parsing ---
SPEC_PATH=""
MODE=""

while [ $# -gt 0 ]; do
  case "$1" in
    --mode)
      MODE="$2"
      shift 2
      ;;
    *)
      if [ -z "$SPEC_PATH" ]; then
        SPEC_PATH="$1"
      fi
      shift
      ;;
  esac
done

if [ -z "$SPEC_PATH" ] || [ -z "$MODE" ]; then
  echo "[ralphharness] ERROR: usage: condense-context.sh <spec_path> --mode <proactive|reactive|emergency>" >&2
  exit 1
fi

case "$MODE" in
  proactive|reactive|emergency) ;;
  *)
    echo "[ralphharness] ERROR: invalid mode '$MODE', must be proactive|reactive|emergency" >&2
    exit 1
    ;;
esac

# --- Degradation Check ---
# If spec dir not writable, skip gracefully (never abort the loop).
if ! spec_dir_writable "$SPEC_PATH"; then
  echo "[ralphharness] WARN: spec dir not writable, skipping condensation ($SPEC_PATH)" >&2
  echo "degraded: spec dir not writable"
  exit 0
fi

# --- Gate Re-check (proactive mode only) ---
# In proactive mode, re-check combined line count before proceeding.
# If lines <= 2000, context is within bounds — no-op.
if [ "$MODE" = "proactive" ]; then
  LINE_COUNT="$(combined_line_count "$SPEC_PATH")"
  if [ "$LINE_COUNT" -le 2000 ]; then
    echo "no-op: combined line count $LINE_COUNT <= 2000"
    exit 0
  fi
fi

# --- Archive First (before any mutation) ---
ARCHIVE_TS="$(date -u +%Y%m%dT%H%M%SZ)"
ARCHIVE_FILE=".archive.${ARCHIVE_TS}.md"
ARCHIVE_PATH="${SPEC_PATH}/${ARCHIVE_FILE}"

{
  echo "# Archive — generated by condense-context.sh at ${ARCHIVE_TS} (UTC)"
  echo "# Mode: ${MODE}"
  echo ""
  echo "## chat.md"
  echo "---"
  if [ -f "${SPEC_PATH}/chat.md" ]; then
    cat "${SPEC_PATH}/chat.md"
  fi
  echo ""
  echo "## .progress.md"
  echo "---"
  if [ -f "${SPEC_PATH}/.progress.md" ]; then
    cat "${SPEC_PATH}/.progress.md"
  fi
} > "$ARCHIVE_PATH"

# --- Pre-Condensation Counts ---
CHAT_LINES_BEFORE=0
PROGRESS_LINES_BEFORE=0
[ -f "${SPEC_PATH}/chat.md" ] && CHAT_LINES_BEFORE="$(wc -l < "${SPEC_PATH}/chat.md")"
[ -f "${SPEC_PATH}/.progress.md" ] && PROGRESS_LINES_BEFORE="$(wc -l < "${SPEC_PATH}/.progress.md")"

# --- Min-pointer Computation ---
MIN_POINTER=0
STATE_FILE="${SPEC_PATH}/.ralph-state.json"
if [ -f "$STATE_FILE" ]; then
  MIN_POINTER="$(jq -r '[.chat.coordinator.lastReadLine // 0, .chat.executor.lastReadLine // 0, .chat.reviewer.lastReadLine // 0] | min' "$STATE_FILE" 2>/dev/null || echo 0)"
fi

# --- Condense chat.md (under flock, fd 200) ---
CHAT_LINES_AFTER=0
CHAT_REWRITTEN=0

if [ -f "${SPEC_PATH}/chat.md" ]; then
  TOTAL_CHAT_LINES="$(wc -l < "${SPEC_PATH}/chat.md")"

  if [ "$MIN_POINTER" -le 0 ]; then
    MIN_POINTER="$TOTAL_CHAT_LINES"
  fi

  # Truncate to file length if pointer exceeds it
  if [ "$MIN_POINTER" -ge "$TOTAL_CHAT_LINES" ]; then
    MIN_POINTER=$(( TOTAL_CHAT_LINES - 1 ))
    [ "$MIN_POINTER" -lt 0 ] && MIN_POINTER=0
  fi

  PREFIX_LINES="$MIN_POINTER"
  SUFFIX_START=$(( MIN_POINTER + 1 ))

  LOCK_FILE="${SPEC_PATH}/chat.md.lock"
  (
    flock -x -w 10 200 || {
      echo "[ralphharness] ERROR: failed to acquire chat.md lock" >&2
      exit 1
    }

    # Extract preserved markers from prefix (lines 1..PREFIX_LINES)
    PRESERVED=""
    PRESERVED="$(awk 'NR <= '"$PREFIX_LINES"' {
      # Control signals (standalone lines)
      if (/^\[HOLD\]$|^\[PENDING\]$|^\[DEADLOCK\]$|^\[URGENT\]$/) { print; next }
      # Collaboration signals
      if (/HYPOTHESIS:|ROOT_CAUSE:|FIX_PROPOSAL:|BUG_DISCOVERY:/) { print; next }
      # Pair-debug markers
      if (/^PAIR-DEBUG:|^Driver:|^Navigator:/) { print; next }
      # Message headers
      if (/^## \[/) { print; next }
    }' "${SPEC_PATH}/chat.md" 2>/dev/null || true)"

    # Extract last 15 message blocks from prefix
    LAST_15_BLOCKS=""
    LAST_15_BLOCKS="$(awk '
      {
        if (/^## \[/) { blocks[++blockCount] = NR }
        lines[NR] = $0
      }
      END {
        start = 1; last = '"$PREFIX_LINES"'
        if (blockCount >= 15) start = blocks[blockCount - 14]
        for (i = start; i <= last; i++) print lines[i]
      }' "${SPEC_PATH}/chat.md" 2>/dev/null || true)"

    # Protected suffix (lines SUFFIX_START..EOF) — verbatim
    SUFFIX=""
    if [ "$SUFFIX_START" -le "$TOTAL_CHAT_LINES" ]; then
      SUFFIX="$(tail -n +"$SUFFIX_START" "${SPEC_PATH}/chat.md" 2>/dev/null || true)"
    fi

    # Build new chat.md: preserved markers + last 15 messages + protected suffix
    {
      if [ -n "$PRESERVED" ]; then
        echo "$PRESERVED"
        echo ""
      fi
      if [ -n "$LAST_15_BLOCKS" ]; then
        echo "$LAST_15_BLOCKS"
        echo ""
      fi
      if [ -n "$SUFFIX" ]; then
        echo "$SUFFIX"
      fi
    } > "${SPEC_PATH}/chat.md.tmp"

    mv "${SPEC_PATH}/chat.md.tmp" "${SPEC_PATH}/chat.md"
    CHAT_REWRITTEN=1

  ) 200>"$LOCK_FILE"

  CHAT_LINES_AFTER="$(wc -l < "${SPEC_PATH}/chat.md" 2>/dev/null || echo 0)"
fi

# --- Condense .progress.md (stable/volatile split) ---
PROGRESS_LINES_AFTER="$PROGRESS_LINES_BEFORE"

if [ -f "${SPEC_PATH}/.progress.md" ]; then
  {
    # Keep ## Goal section verbatim
    awk '/^## Goal/{ found=1; print; next }
         found && /^## /{ if($0 !~ /^## Goal/) exit; print; next }
         found{ print }' "${SPEC_PATH}/.progress.md" 2>/dev/null || true
    echo ""

    # Keep ## Learnings section verbatim
    awk '/^## Learnings/{ found=1; print; next }
         found && /^## /{ if($0 !~ /^## Learnings/) exit; print; next }
         found{ print }' "${SPEC_PATH}/.progress.md" 2>/dev/null || true
    echo ""

    # Keep last 3 task entries from volatile section
    TASK_ENTRIES="$(grep -n '^\- \[x\]\|^\- \[.\]' "${SPEC_PATH}/.progress.md" 2>/dev/null | tail -3 || true)"
    if [ -n "$TASK_ENTRIES" ]; then
      echo "## Recent Task Entries"
      echo ""
      echo "$TASK_ENTRIES"
    fi
  } > "${SPEC_PATH}/.progress.md.tmp"
  mv "${SPEC_PATH}/.progress.md.tmp" "${SPEC_PATH}/.progress.md"
  PROGRESS_LINES_AFTER="$(wc -l < "${SPEC_PATH}/.progress.md" 2>/dev/null || echo 0)"
fi

# --- Update State Pointers (atomic via temp file + mv) ---
if [ "$CHAT_REWRITTEN" -eq 1 ] && [ -f "$STATE_FILE" ]; then
  REMOVED=$(( PREFIX_LINES - CHAT_LINES_AFTER ))
  if [ "$REMOVED" -lt 0 ]; then REMOVED=0; fi

  TEMP_STATE="${STATE_FILE}.tmp"
  jq --argjson removed "$REMOVED" \
    'if .chat then
      .chat.coordinator.lastReadLine = (if (.chat.coordinator.lastReadLine // 0) - $removed < 0 then 0 else (.chat.coordinator.lastReadLine // 0) - $removed end) |
      .chat.executor.lastReadLine = (if (.chat.executor.lastReadLine // 0) - $removed < 0 then 0 else (.chat.executor.lastReadLine // 0) - $removed end) |
      .chat.reviewer.lastReadLine = (if (.chat.reviewer.lastReadLine // 0) - $removed < 0 then 0 else (.chat.reviewer.lastReadLine // 0) - $removed end)
    else . end' "$STATE_FILE" > "$TEMP_STATE" && mv "$TEMP_STATE" "$STATE_FILE"
fi

# --- Log Condensation Metric (fd 201, AFTER flock closes) ---
TOKENS_PCT=0
if [ "$MODE" = "reactive" ] || [ "$MODE" = "emergency" ]; then
  if [ -n "${TRANSCRIPT_PATH:-}" ] && [ -f "${TRANSCRIPT_PATH:-}" ]; then
    TOKENS_PCT="$(transcript_usage_pct "$TRANSCRIPT_PATH")"
  fi
fi

LINE_COUNT_BEFORE="$(combined_line_count "$SPEC_PATH")"
LINE_COUNT_AFTER=$(( CHAT_LINES_AFTER + PROGRESS_LINES_AFTER ))

write_condensation_metric "$SPEC_PATH" "$MODE" "$LINE_COUNT_BEFORE" "$LINE_COUNT_AFTER" "$TOKENS_PCT" "$ARCHIVE_FILE"

# --- Prune Archives (keep newest 3) ---
ARCHIVE_COUNT="$(find "${SPEC_PATH}" -maxdepth 1 -name '.archive.*.md' -type f 2>/dev/null | wc -l)"
if [ "$ARCHIVE_COUNT" -gt 3 ]; then
  REMOVE_COUNT=$(( ARCHIVE_COUNT - 3 ))
  find "${SPEC_PATH}" -maxdepth 1 -name '.archive.*.md' -type f -printf '%T@ %p\n' 2>/dev/null \
    | sort -n \
    | head -n "$REMOVE_COUNT" \
    | awk '{print $2}' \
    | xargs rm -f 2>/dev/null || true
fi

# --- Output Summary ---
echo "condensed: chat ${CHAT_LINES_BEFORE}->${CHAT_LINES_AFTER}, progress ${PROGRESS_LINES_BEFORE}->${PROGRESS_LINES_AFTER}"
